/**
 * Shared color scheme for extension and webview layers.
 */

const BASE_COLORS = {
  WHITE: "#ffffff",
  BLACK: "#000000",
  GRAY_333: "#333",
  GRAY_555: "#555",
  GRAY_666: "#666",
  GRAY_6F: "#6f6f6f",
  GRAY_2F: "#2f2f2f",
  GRAY_999: "#999",
  GRAY_CCC: "#ccc",
  GRAY_DDD: "#ddd",
  GRAY_EEE: "#eee",
  GRAY_BBB: "#bbb",
  GRAY_B5: "#b5b5b5",
  GRAY_D3: "#d3d3d3",
  GRAY_F3: "#f3f3f3",
  GRAY_F1: "#f1f1f1",
  GRAY_E0: "#e0e0e0",
  GRAY_F9: "#f9f9f9",
  GRAY_F7: "#f7f7f7",
  BLUE_0066CC: "#0066cc",
  BLUE_0052A3: "#0052a3",
  BLUE_2255FF: "#2255FF",
  BLUE_3367D6: "#3367d6",
  GREEN_28A745: "#28a745",
  GREEN_218838: "#218838",
  GREEN_22DD22: "#22DD22",
  GREEN_7BBD88: "#7bbd88",
  GREEN_2E7D32: "#2e7d32",
  ORANGE_B76E00: "#b76e00",
  ORANGE_FF8800: "#ff8800",
  RED_B00020: "#b00020",
  RED_CC0000: "#cc0000",
  GOLD_FFD700: "#FFD700",
  CANVAS_GRID: "#d4d2d2",
  CANVAS_NODE_BORDER: "#2c2c2c",
  CANVAS_NODE_LABEL: "#1a1a1a",
  CANVAS_PORT_NAME: "#222",
  CANVAS_SHADOW: "rgba(0,0,0,0.2)",
  CANVAS_LEGEND_BG: "rgba(255, 255, 255, 0.95)",
  CANVAS_EMPTY_TEXT: "#aaa",
  PALETTE_LIB_BG: "#f0f0f0",
  PALETTE_FOLDER_HOVER: "#f5f5f5",
  PALETTE_BLOCK_HOVER: "#e8f4f8",
} as const;

export const COLOR_SCHEME = {
  // General UI colors (webview)
  UI: {
    // Text colors
    TEXT_PRIMARY: BASE_COLORS.GRAY_333,
    TEXT_SECONDARY: BASE_COLORS.GRAY_555,
    TEXT_MUTED: BASE_COLORS.GRAY_999,
    TEXT_LIGHT: BASE_COLORS.GRAY_666,

    // Palette - Library headers (root level)
    PALETTE_LIB_HEADER_BG: BASE_COLORS.PALETTE_LIB_BG,
    PALETTE_LIB_HEADER_BORDER: BASE_COLORS.GRAY_DDD,

    // Palette - Folder headers
    PALETTE_FOLDER_BG_HOVER: BASE_COLORS.PALETTE_FOLDER_HOVER,

    // Palette - Block items
    PALETTE_BLOCK_BG_HOVER: BASE_COLORS.PALETTE_BLOCK_HOVER,
    PALETTE_BLOCK_BG_TRANSPARENT: "transparent",

    // Buttons - Primary (green)
    BUTTON_PRIMARY_BG: BASE_COLORS.GREEN_28A745,
    BUTTON_PRIMARY_BG_HOVER: BASE_COLORS.GREEN_218838,
    BUTTON_PRIMARY_TEXT: BASE_COLORS.WHITE,

    // Buttons - Secondary (gray)
    BUTTON_SECONDARY_BG: BASE_COLORS.GRAY_F1,
    BUTTON_SECONDARY_BG_HOVER: BASE_COLORS.GRAY_E0,
    BUTTON_SECONDARY_TEXT: BASE_COLORS.GRAY_2F,
    BUTTON_SECONDARY_BORDER: BASE_COLORS.GRAY_B5,

    // UI elements
    UI_BORDER: BASE_COLORS.GRAY_BBB,
    UI_ACTIVE_BG: BASE_COLORS.GRAY_F1,

    // Links
    LINK_TEXT: BASE_COLORS.BLUE_0066CC,
    LINK_TEXT_HOVER: BASE_COLORS.BLUE_0052A3,

    // States
    ERROR_TEXT: BASE_COLORS.RED_B00020,
    SUCCESS_TEXT: BASE_COLORS.GREEN_2E7D32,
    WARNING_TEXT: BASE_COLORS.ORANGE_B76E00,
    STATUS_SAVING: BASE_COLORS.BLUE_3367D6,

    // Input fields
    INPUT_BORDER: BASE_COLORS.GRAY_CCC,
    INPUT_TEXT: BASE_COLORS.GRAY_6F,

    // Buttons - disabled states
    BUTTON_DISABLED_BG: BASE_COLORS.GREEN_7BBD88,
    BUTTON_TEXT_WHITE: BASE_COLORS.WHITE,
    BUTTON_REMOVE_BG: BASE_COLORS.GRAY_F7,

    // Borders & dividers
    BORDER_COLOR: BASE_COLORS.GRAY_DDD,
    DIVIDER_COLOR: BASE_COLORS.GRAY_EEE,

    // Empty states
    EMPTY_STATE_BG: "transparent",
    EMPTY_STATE_TEXT: BASE_COLORS.GRAY_666,

    // Logging colors
    LOG_DEBUG: BASE_COLORS.GRAY_666,
    LOG_INFO: BASE_COLORS.BLUE_0066CC,
    LOG_WARN: BASE_COLORS.ORANGE_FF8800,
    LOG_ERROR: BASE_COLORS.RED_CC0000,
  },

  // Extension-hosted HTML colors (toolbar, panels)
  EXTENSION: {
    PANEL_BG: BASE_COLORS.WHITE,
    PANEL_HEADER_BG: BASE_COLORS.GRAY_F3,
    PANEL_HEADER_BORDER: BASE_COLORS.GRAY_DDD,

    TOOLBAR_BG: BASE_COLORS.GRAY_F3,
    TOOLBAR_BORDER: BASE_COLORS.GRAY_DDD,
    TOOLBAR_BUTTON_PRIMARY_BG: BASE_COLORS.GREEN_28A745,
    TOOLBAR_BUTTON_PRIMARY_HOVER: BASE_COLORS.GREEN_218838,
    TOOLBAR_BUTTON_PRIMARY_TEXT: BASE_COLORS.WHITE,
    TOOLBAR_BUTTON_PRIMARY_BORDER: BASE_COLORS.GRAY_BBB,
    TOOLBAR_BUTTON_SECONDARY_BG: BASE_COLORS.GRAY_E0,
    TOOLBAR_BUTTON_SECONDARY_HOVER: BASE_COLORS.GRAY_D3,
    TOOLBAR_BUTTON_SECONDARY_TEXT: BASE_COLORS.GRAY_2F,
    TOOLBAR_BUTTON_SECONDARY_BORDER: BASE_COLORS.GRAY_B5,

    TEXT_PRIMARY: BASE_COLORS.GRAY_333,
    TEXT_SECONDARY: BASE_COLORS.GRAY_555,
    TEXT_MUTED: BASE_COLORS.GRAY_666,

    BORDER_DEFAULT: BASE_COLORS.GRAY_DDD,
    BORDER_LIGHT: BASE_COLORS.GRAY_EEE,

    DEVICE_LABEL_COLOR: BASE_COLORS.GRAY_666,
    DEVICE_VALUE_COLOR: BASE_COLORS.GRAY_333,
    DEVICE_SECTION_BG: BASE_COLORS.GRAY_F9,
    EMPTY_TEXT: BASE_COLORS.GRAY_999,
    INPUT_BORDER: BASE_COLORS.GRAY_CCC,
    INPUT_TEXT: BASE_COLORS.GRAY_6F,
  },

  // Canvas rendering colors
  CANVAS: {
    NODE_BACKGROUND_COLOR: BASE_COLORS.WHITE,
    NODE_BORDER_COLOR: BASE_COLORS.CANVAS_NODE_BORDER,
    NODE_SHADOW_COLOR: BASE_COLORS.CANVAS_SHADOW,
    NODE_LABEL_COLOR: BASE_COLORS.CANVAS_NODE_LABEL,

    EVENT_PORT_COLOR: BASE_COLORS.GREEN_22DD22,
    DATA_PORT_COLOR: BASE_COLORS.BLUE_2255FF,
    PORT_TYPE_COLOR: BASE_COLORS.WHITE,
    PORT_NAME_COLOR: BASE_COLORS.CANVAS_PORT_NAME,
    PORT_VALUE_COLOR: BASE_COLORS.BLACK,
    PORT_DEFAULT_VALUE_COLOR: BASE_COLORS.GRAY_666,

    EVENT_CONNECTION_COLOR: BASE_COLORS.GREEN_22DD22,
    DATA_CONNECTION_COLOR: BASE_COLORS.BLUE_2255FF,

    GRID_COLOR: BASE_COLORS.CANVAS_GRID,

    LEGEND_BACKGROUND_COLOR: BASE_COLORS.CANVAS_LEGEND_BG,
    LEGEND_BORDER_COLOR: BASE_COLORS.GRAY_999,
    LEGEND_TEXT_COLOR: BASE_COLORS.GRAY_333,

    STATS_TEXT_COLOR: BASE_COLORS.GRAY_333,

    EMPTY_NODES_COLOR: BASE_COLORS.CANVAS_EMPTY_TEXT,

    SELECTION_STROKE_COLOR: BASE_COLORS.GOLD_FFD700,
  },
} as const;

// Backwards-compatible aliases for existing imports.
export const COLORS = COLOR_SCHEME.UI;
export const EXTENSION_COLORS = COLOR_SCHEME.EXTENSION;
export const CANVAS_COLORS = COLOR_SCHEME.CANVAS;
